name: 'GitVersion Action'
description: 'Determines the version of the code using GitVersion'
outputs:
  fullSemVer:
    description: "Full semantic version"
    value: ${{ steps.version_step.outputs.semVer }}-${{ steps.version_step.outputs.buildMetaData }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.2.0
      with:
        versionSpec: '6.4.x'
    
    - name: Determine Version
      id: version_step # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v4.2.0
      with:
        configFilePath: '.gitversion.yaml'