name: 'Python Unit Tests Action'
description: 'Runs unit tests'
inputs:
  SCA_SOURCES:
    description: 'Sources to scan'
    required: true
  PYTHON_VERSION:
    description: 'Python version to use'
    required: true
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ inputs.PYTHON_VERSION }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
      shell: bash
    - name: Test with tox
      run: tox -e coverage -- --junitxml=pytest-junit.xml
      shell: bash
    - name: Upload unit test reports
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-reports
        path: |
          pytest-junit.xml
          .coverage
          coverage.xml
          htmlcov/
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
          pytest-junit.xml