name: 'Docker Build Action'
description: 'Builds a Docker image and pushes it to GitHub Container Registry'
inputs:
  COMP_NAME:
    description: 'Component Name'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
outputs:
  build-version:
    description: "Build version"
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: repo-name-lowercase
      name: Convert repository owner to lowercase
      uses: ASzc/change-string-case-action@v2
      with:
        string: "${{ github.repository_owner }}"

    - uses: actions/checkout@v5

    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: "ghcr.io/${{ steps.repo-name-lowercase.outputs.lowercase }}/${{ env.COMP_NAME }}:${{ steps.version.outputs.version }}"