name: 'Helm Test Action'
description: 'Performs linting and testing of Helm charts'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.1

    - uses: actions/setup-python@v6.0.0
      with:
        python-version: '3.x'
        check-latest: true

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
      shell: bash

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.8.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --target-branch ${{ github.event.repository.default_branch }} --config ct.yaml
      shell: bash

    - name: Create kind cluster
      if: steps.list-changed.outputs.changed == 'true'
      uses: helm/kind-action@v1.12.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Load images into kind
      if: steps.list-changed.outputs.changed == 'true'
      run: |
        for chart in $(ct list-changed --target-branch ${{ github.event.repository.default_branch }}); do
          image=$(yq e '.image.repository + ":" + .image.tag' "./${chart}/values.yaml")
          docker pull "$image"
          kubectl cluster-info --context kind-chart-testing
          kind load docker-image "$image" --name chart-testing
        done
      shell: bash

    - name: Run chart-testing (install)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct install --target-branch ${{ github.event.repository.default_branch }} --config ct.yaml
      shell: bash