name: 'Release Action'
description: 'Automatically bumping the minor version, creating a git tag and pushing it to the repository'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
outputs:
  new_tag:
    description: "New Tag"
    value: ${{ steps.tagging.outputs.new_tag }}
  old_tag:
    description: "Old Tag"
    value: ${{ steps.tagging.outputs.old_tag }}
  tag:
    description: "The value of the latest tag after running this action"
    value: ${{ steps.tagging.outputs.tag }}
  part:
    description: "The part of version which was bumped"
    value: ${{ steps.tagging.outputs.part }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Bump version and push tag
      id: tagging
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        DEFAULT_BUMP: "none"
        