name: 'Promote Action'
description: 'Promotes a Docker image to a new version tag'
inputs:
  COMP_NAME:
    description: 'Component Name'
    required: true
  CHART_NAME:
    description: 'Helm Chart Name'
    required: false
  BUILD_VERSION:
    description: 'Build Version'
    required: true
  TARGET_REGISTRY:
    description: 'Target Registry'
    required: false
  TARGET_VERSION:
    description: 'Target Version'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - id: repo-name-lowercase
      name: Convert repository owner to lowercase
      uses: ASzc/change-string-case-action@v2
      with:
        string: "${{ github.repository_owner }}"

    - uses: imjasonh/setup-crane@v0.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: promote-image
      run: |
        if [ -z "${{ inputs.TARGET_REGISTRY }}" ]; then
          TARGET_REGISTRY="ghcr.io/${{ steps.repo-name-lowercase.outputs.lowercase }}"
        else
          TARGET_REGISTRY="${{ inputs.TARGET_REGISTRY }}"
        fi
        echo "Promoting image for ${{ env.COMP_NAME }}"
        crane auth login -u ${{ github.actor }} -p ${{ inputs.GITHUB_TOKEN }} ghcr.io
        crane cp ghcr.io/${{ steps.repo-name-lowercase.outputs.lowercase }}/${{ env.COMP_NAME }}:${{ inputs.BUILD_VERSION }} $TARGET_REGISTRY/${{ env.COMP_NAME }}:${{ inputs.TARGET_VERSION }}
        if [ -n "${{ inputs.CHART_NAME }}" ]; then
          echo "Also promoting Helm chart for ${{ inputs.CHART_NAME }}"
          crane cp ghcr.io/${{ steps.repo-name-lowercase.outputs.lowercase }}/charts/${{ inputs.CHART_NAME }}:${{ inputs.BUILD_VERSION }} $TARGET_REGISTRY/charts/${{ inputs.CHART_NAME }}:${{ inputs.TARGET_VERSION }}
        fi
      shell: bash
