name: 'Promote Action'
description: 'Promotes a Docker image to a new version tag'
inputs:
  COMP_NAME:
    description: 'Component Name'
    required: true
runs:
  using: "composite"
  steps:
    - id: repo-name-lowercase
      name: Convert repository owner to lowercase
      uses: ASzc/change-string-case-action@v2
      with:
        string: "${{ github.repository_owner }}"

    - uses: actions/checkout@v5

    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.6

    - uses: imjasonh/setup-crane@v0.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: promote-image
      run: |
        CALCULATED_RELEASE_VERSION=$(get_release_version)
        echo "CALCULATED_RELEASE_VERSION=${CALCULATED_RELEASE_VERSION}"
        echo "Promoting image for ${{ env.COMP_NAME }}"
        crane auth login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
        crane tag ghcr.io/${{ steps.repo-name-lowercase.outputs.lowercase }}/${{ env.COMP_NAME }}:${{ needs.build.outputs.build-version }} ${{ steps.version.outputs.version }}
      shell: bash
