name: 'Promote Action'
description: 'Promotes a Docker image to a new version tag'
inputs:
  COMP_NAME:
    description: 'Component Name'
    required: true
  CHART_NAME:
    description: 'Helm Chart Name'
    required: false
    default: ''
  BUILD_VERSION:
    description: 'Build Version'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - id: repo-name-lowercase
      name: Convert repository owner to lowercase
      uses: ASzc/change-string-case-action@v2
      with:
        string: "${{ github.repository_owner }}"

    - uses: actions/checkout@v5

    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.6

    - uses: imjasonh/setup-crane@v0.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: promote-image
      run: |
        echo "Promoting image for ${{ env.COMP_NAME }}"
        crane auth login -u ${{ github.actor }} -p ${{ inputs.GITHUB_TOKEN }} ghcr.io
        crane tag ghcr.io/${{ steps.repo-name-lowercase.outputs.lowercase }}/${{ env.COMP_NAME }}:${{ inputs.BUILD_VERSION }} ${{ steps.version.outputs.version }}
        if: [ -n "${{ inputs.CHART_NAME }}" ]; then
          echo "Also promoting Helm chart for ${{ inputs.CHART_NAME }}"
          crane tag ghcr.io/${{ steps.repo-name-lowercase.outputs.lowercase }}/charts/${{ inputs.CHART_NAME }}:${{ inputs.BUILD_VERSION }} ${{ steps.version.outputs.version }}
        fi
      shell: bash
